caption_model: newfc
input_json: ./data/cocotalk.json
input_fc_dir: ./data/cocotalk_fc
input_att_dir: ./data/cocotalk_att
input_label_h5: ./data/cocotalk_label.h5
learning_rate: 0.0025
learning_rate_decay_start: 100
scheduled_sampling_start: 150
# checkpoint_path: $ckpt_path
# $start_from
language_eval: 1
save_checkpoint_every: 100
val_images_use: 5000

batch_size: 50
max_epochs: 100

beam_size: 5
paired_percentage: 0.01
language_pretrain_epoch: 2
paired_train_epoch: 2
random_seed: 0
weight_decay: 0.0005
alpha: 0.99
label_smoothing: 0
hyper_parameter_lambda_y: 0
hyper_parameter_lambda_x: 0.1
std_pseudo_visual_feature: 0.1
number_of_models: 3
inner_iteration: 100
